version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2
  sue445-bundle-install: sue445/bundle-install@volatile

jobs:
  validate:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/app
    steps:
      - checkout
      - run: circleci orb validate src/orb.yml

  smoke_test:
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/app
    steps:
      - checkout
      - sue445-bundle-install/bundle-install:
          cache_key_prefix: "v1-bundle"
          bundle_jobs: 4
          bundle_retry: 3
          bundle_path: "vendor/bundle"
          bundle_clean: true
          restore_bundled_with: true

workflows:
  version: 2

  # c.f. https://github.com/CircleCI-Public/hello-orb/blob/c43a73505b996c29688510b5d60d17130ae937b7/.circleci/config.yml
  btd:
    jobs:
      - validate

      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires:
            - validate

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "sue445/bundle-install@dev:${CIRCLE_BRANCH}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]

      - smoke_test:
          requires: [orb-tools/publish]

      - orb-tools/increment:
          orb-path: packed/orb.yml
          orb-ref: "sue445/bundle-install"
          segment: "patch"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [smoke_test]
          filters:
            branches:
              only: master
